#!/bin/bash
apt-get update -y
apt-get upgrade -y
apt-get install -y nginx
systemctl start nginx
systemctl enable nginx
apt-get install -y git
curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
apt-get install -y nodejs
git clone https://github.com/debjyoti6/aws.git
cd aws
npm install
node index.js

cd /
cd etc
cd nginx
cd sites-available
sudo nano default
sudo systemctl restart nginx

proxy_pass http://localhost:4000;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection 'Upgrade';
proxy_set_header Host $host;
proxy_cache_bypass $http_upgrade;


git init
git config --global user.name "Debjyoti"
git config --global user.email "debjyotisantra6@email.com"
git add .
git commit -m "first commit"
git remote add origin https://github.com/debjyoti6/new.git
git branch -M main
git push -u origin main
